apiVersion: apps/v1
kind: Deployment
metadata:
  name: apphealthexample-deployment
  labels:
    app: apphealthexample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apphealthexample
  template:
    metadata:
      labels:
        app: apphealthexample
    spec:
      containers:
      - name: apphealthexample
        image: local/apphealtexample
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command:
              - find
              - alive.txt
              - -mmin
              - '-1'
          initialDelaySeconds: 15
          periodSeconds: 15